code/Ride_Rentals/Ride_Rentals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]


if settings.DEBUG: # Only do this in development! For production, configure your web server
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/Ride_Rentals/mainapp/urls.py
# Built by crackspy

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # Homepage URL
    path('', views.index, name='home'),

    # Authentication URLs
    path('auth/', views.auth_page, name='auth'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

    # Password reset URLs
    path(
        'password_reset/', 
        views.CustomPasswordResetView.as_view(template_name='mainapp/login/password_reset.html'), 
            name='password_reset'
        ),
    path(
        'password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='mainapp/login/password_reset_done.html'), 
            name='password_reset_done'),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='mainapp/login/password_reset_confirm.html'), 
            name='password_reset_confirm'),
    path(
        'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='mainapp/login/password_reset_complete.html'), 
            name='password_reset_complete'),

    # User profile URLs
    path('profile/', views.profile_dashboard, name='profile'),
    path('profile/change_password/',
         auth_views.PasswordChangeView.as_view(template_name='mainapp/profile/change_password.html'),
         name='change_password'),
    path('profile/change_password/done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='mainapp/profile/change_password_done.html'),
        name='password_change_done'),
    path('profile/update/', views.update_profile, name='update_profile'),

    # Car rental URLs
    path('cars/', views.explore_cars, name='explore_cars'),
    path('success/', views.success_page, name="success_page"),
    path('booking/<slug:slug>', views.booking, name='booking'),
    path('confirm_booking/<slug:slug>/', views.confirm_booking, name='confirm_booking'),
    path('payment_success/<int:booking_id>/', views.payment_success, name='payment_success'),
    path('add-to-wishlist/<slug:slug>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<slug:slug>/', views.remove_from_wishlist, name='remove_from_wishlist'),

]

code/Ride_Rentals/mainapp/models.py
# Built by crackspy

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.text import slugify
from django.core.exceptions import ValidationError
import uuid
import os


# Profile details
def profile_image_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4().hex}.{ext}"  # Random string filename
    return os.path.join('images/profile_pics/', filename)

# Function to validate file size
def validate_file_size(value):
    limit = 5 * 1024 * 1024  # 5MB limit
    if value.size > limit:
        raise ValidationError("File size must be less than 5MB.")

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(
        upload_to=profile_image_path,
        blank=True,
        null=True,
        default='images/profile_pics/default.png',
        validators=[validate_file_size]
    )
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    def save(self, *args, **kwargs):
        try:
            old_profile = Profile.objects.get(pk=self.pk)
            if old_profile.profile_picture and old_profile.profile_picture.url != '/media/images/profile_pics/default.png':
                if old_profile.profile_picture != self.profile_picture:
                    if os.path.isfile(old_profile.profile_picture.path):
                        os.remove(old_profile.profile_picture.path)
        except Profile.DoesNotExist:
            pass  # New profile, no old image to delete

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """Delete profile image when profile is deleted."""
        if self.profile_picture and self.profile_picture.url != '/media/images/profile_pics/default.png':
            if os.path.isfile(self.profile_picture.path):
                os.remove(self.profile_picture.path)
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.user.username


# Car details
class Car_info(models.Model):
    def image_upload_path(instance, filename):
        ext = os.path.splitext(filename)[-1]  # Get the file extension
        new_filename = f"{instance.slug}{ext}"  # Format filename using slug
        return os.path.join("images/car_pics", new_filename)  # Store in media/images/car_pics/
    
    img = models.ImageField(upload_to=image_upload_path)  # Upload path updated
    name = models.CharField(max_length=50)
    year = models.IntegerField(default=2024)
    capacity = models.IntegerField(null=False)
    mileage = models.FloatField(null=False)

    class Engine(models.TextChoices):
        Hybrid = 'Hybrid'
        Petrol = 'Petrol'
        Diesel = 'Diesel'

    class Transmission(models.TextChoices):
        Manual = 'Manual'
        Automatic = 'Automatic'

    engine = models.CharField(
        max_length=10,
        choices=Engine.choices,
        default=Engine.Petrol,
    )

    transmission = models.CharField(
        max_length=15,
        choices=Transmission.choices,
        default=Transmission.Manual,
    )

    available = models.BooleanField(default=True)
    rent = models.FloatField(default=0.0)
    slug = models.SlugField(max_length=100, unique=True, blank=True)  # Unique slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Car_info, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


#  Booking details
class Booking(models.Model):
    cus_name = models.CharField(max_length=50)
    cus_ph = models.CharField(max_length=15)
    cus_email = models.EmailField(max_length=254)

    # ForeignKey to Car_info
    car = models.ForeignKey('Car_info', on_delete=models.CASCADE)

    # ForeignKey to User (Customer)
    cus_username = models.ForeignKey(User, on_delete=models.CASCADE)

    class Status(models.TextChoices):
        BOOKED = 'Booked'
        RENTED = 'Rented'
        COMPLETED = 'Completed'

    class Payment_method(models.TextChoices):
        UPI = 'UPI'
        CARD = 'Card'
        CashOnDelivery = 'Cash on Delivery'

    class Payment_Status(models.TextChoices):
        PAID = 'Paid'
        PENDING = 'Pending'

    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.BOOKED,  # Default value is 'Booked'
    )

    payment_method = models.CharField(
        max_length=50,
        choices=Payment_method.choices,
        default=Payment_method.CashOnDelivery, # Default value is 'COD'
    )

    payment_status = models.CharField(
        max_length=10,
        choices=Payment_Status.choices,
        default=Payment_Status.PENDING,  # Default value is 'Pending'
    )


    pickup_date = models.DateField()
    return_date = models.DateField()
    booked_on = models.DateField(auto_now=True)
    rent = models.DecimalField(max_digits=10, decimal_places=2) # Car price
    total_rent = models.DecimalField(max_digits=10, decimal_places=2) # Computed total rent

    def save(self, *args, **kwargs):
        # Update car availability when status is set to 'completed'
        if self.status == Booking.Status.COMPLETED:
            self.car.available = True 
            self.car.save()
        
        super(Booking, self).save(*args, **kwargs)  # Call the original save method

    def __str__(self):
        return f"Booking by {self.cus_name} for {self.car.name}"

# Wishlists
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # ForeignKey to User
    car = models.ForeignKey(Car_info, on_delete=models.CASCADE)  # ForeignKey to Car_info
    added_on = models.DateTimeField(auto_now_add=True)  # Timestamp when added to wishlist

    class Meta:
        unique_together = ('user', 'car')  # Ensures a user cannot add the same car twice

    def __str__(self):
        return f"{self.user.username} - {self.car.name}" 


# receivers

# delete old car image 
@receiver(post_delete, sender=Car_info)
def delete_event_image(sender, instance, **kwargs):
    if instance.img and os.path.isfile(instance.img.path):
        instance.img.delete(save=False)

# create profile
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

# save profile
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

code/Ride_Rentals/mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
import os

class ProfileUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(max_length=15, required=False)
    set_default_picture = forms.BooleanField(required=False)
    
    class Meta:
        model = Profile
        fields = ['profile_picture']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        if user:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name
            self.fields['email'].initial = user.email 

    def save(self, user):
        """Save profile changes and handle setting default image."""
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.save()

        profile = user.profile
        profile.phone_number = self.cleaned_data['phone_number']

        if self.cleaned_data.get("set_default_picture"):
            # If the hidden field is True, set default image
            profile.profile_picture = "images/profile_pics/default.png"
        elif self.cleaned_data.get("profile_picture"):
            # If a new image is provided, update it
            profile.profile_picture = self.cleaned_data["profile_picture"]
        
        profile.save()
        return profile

code/Ride_Rentals/templates/mainapp/profile/change_password.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %} Profile - {{ user.username }} {% endblock %}

{% block head %}

<link rel="stylesheet" href="{% static 'mainapp/css/password-reset.css' %}">

{% endblock %}

{% block content %}
<div class="password-reset-container content-pd-t70">
    <div class="password-reset-content">
        <div class="password-confirm">
            <div class="password-confirm-head">
                <i><a href="{% url 'profile' %}">
                        <ion-icon name="arrow-back-circle-outline"></ion-icon>
                    </a>
                </i>
                <div class="password-confirm-head-h1-div">
                    <h2>Change Your Password</h2>
                </div>
            </div>

            <form method="post" onsubmit="validatePassword(event)" id="new_password_form">
                {% csrf_token %}

                <div class="form-group-div">
                    <label for="id_old_password">Old password:</label>
                    <div class="form-group">
                        <input type="password" name="old_password" id="id_old_password" placeholder="Old password"
                            required>
                        <i class="visibility-toggle-icon"
                            onclick="togglePassword('id_old_password', 'toggleIconOld_p')">
                            <ion-icon id="toggleIconOld_p" name="eye-outline"></ion-icon>
                        </i>
                    </div>
                </div>

                <div class="form-group-div">
                    <label for="id_new_password1">New password:</label>
                    <div class="form-group">
                        <input type="password" name="new_password1" id="id_new_password1" placeholder="New password"
                            required>
                        <i class="visibility-toggle-icon"
                            onclick="togglePassword('id_new_password1', 'toggleIconNew_p1')">
                            <ion-icon id="toggleIconNew_p1" name="eye-outline"></ion-icon>
                        </i>
                    </div>
                </div>

                <div class="rules">
                    <h3>Password Requirements:</h3>
                    <ul>
                        <li id="upperCase"><ion-icon name="close-circle-outline"></ion-icon> Upper Case Character</li>
                        <li id="lowerCase"><ion-icon name="close-circle-outline"></ion-icon> Lower Case Character</li>
                        <li id="minLength"><ion-icon name="close-circle-outline"></ion-icon> At least 8s characters</li>
                        <li id="number"><ion-icon name="close-circle-outline"></ion-icon> Numeric Character</li>
                        <li id="special"><ion-icon name="close-circle-outline"></ion-icon> Special Character</li>
                        <li id="matchPassword"><ion-icon name="close-circle-outline"></ion-icon> Passwords Match</li>
                    </ul>
                </div>

                <div class="form-group-div">
                    <label for="id_new_password2">New password confirmation:</label>
                    <div class="form-group">
                        <input type="password" name="new_password2" id="id_new_password2" placeholder="Confirm password"
                            required>
                        <i class="visibility-toggle-icon"
                            onclick="togglePassword('id_new_password2', 'toggleIconNew_p2')">
                            <ion-icon id="toggleIconNew_p2" name="eye-outline"></ion-icon>
                        </i>
                    </div>
                </div>

                <button type="submit" class="btn">Change my password</button>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'mainapp/js/password-reset.js' %}"></script>
{% endblock %}

code/Ride_Rentals/templates/mainapp/profile/change_password_done.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}Password Changed Successfully{% endblock %}

{% block head %}

<link rel="stylesheet" href="{% static 'mainapp/css/password-reset.css' %}">

{% endblock %}

{% block content %}

<div class="password-reset-container">
    <div class="password-reset-content">
        <h2>Password Changed Successfully</h2>
        <p>Your password has been changed successfully.</p>
        <div class="done-btns">
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'profile' %}">Profile</a>
        </div>
    </div>
</div>
{% endblock %}

code/Ride_Rentals/templates/mainapp/profile/profile.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %} Profile - {{ user.username }} {% endblock %}

{% block head %}

<link rel="stylesheet" href="{% static 'mainapp/css/profile.css' %}" />

{% endblock %}

{% block content %}
<div class="dashboard-container">
    <!-- Sidebar Toggle Button -->
    <div class="sidebar-toggle" id="sidebarToggle">
        <ion-icon name="arrow-forward"></ion-icon>
    </div>

    <!-- Sidebar -->
    <div class="sidebar" id="sidebar">
        <div class="profile-icon">
            {% if user_profile.profile_picture and user_profile.profile_picture.url %}
            <img src="{{ user_profile.profile_picture.url }}" alt="Profile Image" />
            {% else %}
            <img src="{% static 'mainapp/images/home/profile.png' %}" alt="Default Profile Image" />
            {% endif %}
        </div>
        <h5 class="usrname m-b-10 fz-18">{{ user.username|title }}</h5>
        <p class="email m-b-10">{{ user.email }}</p>
        <button onclick="openSettingsPopup()">Settings</button>
        <button><a href="{% url 'logout' %}">Logout</a></button>
    </div>

    <!-- Main Content -->
    <div class="content">
        <!-- Wishlist Card -->
        <div class="card">
            <h5>Wishlist</h5>
            {% if wishlist_item %}
            <p>{{ wishlist_item.car.name }}</p>
            <button onclick="openWishlistPopup()">View All Wishlist</button>
            {% else %}
            <p>Your wishlist is empty.</p>
            {% endif %}
        </div>

        <!-- Bookings Card -->
        <div class="card">
            <h5>Your Bookings</h5>
            {% if booking_item %}
            <p>{{ booking_item.car.name }}</p>
            <button onclick="openBookingPopup()">View All Bookings</button>
            {% else %}
            <p>You have no bookings yet.</p>
            {% endif %}
        </div>
    </div>
</div>

<!-- Popup for Settings -->
<div id="settingsPopup" class="popup">
    <div class="popup-head">
        <h3>Settings</h3>
        <span class="close" onclick="closeSettingsPopup()">&times;</span>
    </div>

    <div class="popup-content">
        <!-- Change Password Section -->
        <div class="settings-card">
            <div class="card-body">
                <h4>Change Password</h4>
                <p>
                    If you'd like to update your password, click the button
                    below:
                </p>
                <a href="{% url 'change_password' %}" class="btn btn-change_p">
                    <i><ion-icon name="lock-closed-outline"></ion-icon></i>
                    <span>Change Password</span>
                </a>
            </div>
        </div>

        <!-- Update Profile Section -->
        <div class="settings-card">
            <div class="card-body">
                <h4>Update Profile</h4>
                <p>Update your personal information:</p>
                <a href="{% url 'update_profile' %}" class="btn btn-update">
                    <i><ion-icon name="create-outline"></ion-icon> </i>
                    <span>Update Profile</span>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Popup for All Wishlist Items -->
<div id="wishlistPopup" class="popup">
    <div class="popup-head">
        <h3>Your Wishlist</h3>
        <span class="close" onclick="closeWishlistPopup()">&times;</span>
    </div>

    <div class="popup-content">
        {% for item in all_wishlist_items %}
        <div class="item">
            <div class="item-icon">
                <img src="{{ item.car.img.url }}" alt="{{ car.name }}" loading="lazy" width="200" height="150" />
            </div>
            <div class="item-content">
                <h1>{{ item.car.name }} - {{ item.car.year }}</h1>
                <div class="pos-b">
                    <ul>
                        <li>Rent : ₹{{ item.car.rent }}/ month</li>
                    </ul>
                    <a href="{% url 'remove_from_wishlist' item.car.slug %}" class="fav-btn btn"
                        aria-label="Remove from favourite list">
                        <ion-icon name="heart-dislike-outline"></ion-icon>
                    </a>
                    {% if item.car.available %}
                    <a href="{% url 'booking' item.car.slug %}" class="btn">Book Now</a>
                    {% else %}
                    <span class="not-available">Not Available</span>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Popup for All Bookings -->
<div id="bookingPopup" class="popup">
    <div class="popup-head">
        <h3>Your Bookings</h3>
        <span class="close" onclick="closeBookingPopup()">&times;</span>
    </div>

    <div class="popup-content">
        {% for item in all_bookings %}
        <div class="item">
            <div class="item-icon">
                <img src="{{ item.car.img.url }}" alt="{{ car.name }}" loading="lazy" width="200" height="150" />
            </div>
            <div class="item-content">
                <h1>{{ item.car.name }} - {{ item.car.year }}</h1>
                <div class="booking-info">
                    <ul>
                        <li>
                            <ion-icon name="cash-outline" class="icon-b"></ion-icon>
                            <strong>Rent :</strong> ₹{{ item.car.rent }}/month
                        </li>
                        <li>
                            <ion-icon name="calendar-outline" class="icon-b"></ion-icon>
                            <strong>Pick-up Date :</strong>{{ item.pickup_date }}
                        </li>
                        <li>
                            <ion-icon name="calendar-outline" class="icon-b"></ion-icon>
                            <strong>Return Date :</strong>{{ item.return_date }}
                        </li>
                        <li>
                            <ion-icon name="calculator-outline" class="icon-b"></ion-icon>
                            <strong>Total Rent :</strong>₹{{ item.total_rent }}
                        </li>
                        <li>
                            <ion-icon name="cog" class="icon-b"></ion-icon>
                            <strong>Payment Status :</strong>
                            <span class="status {{ item.payment_status | lower }}">
                                {{ item.payment_status | title }}</span>
                        </li>
                        <li>
                            <ion-icon name="book" class="icon-b"></ion-icon>
                            <strong>Booking Status :</strong>
                            <span class="status {{ item.status | lower }}">{{ item.status | title }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script src="{% static 'mainapp/js/profile.js' %}"></script>

{% endblock %}

code/Ride_Rentals/templates/mainapp/profile/update_profile.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %} Profile - {{ user.username }} {% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'mainapp/css/password-reset.css' %}">
<link rel="stylesheet" href="{% static 'mainapp/css/update-profile.css' %}">
{% endblock %}

{% block content %}
<div class="password-reset-container content-pd-t70">
    <div class="password-reset-content">
        <div class="password-confirm">
            <div class="password-confirm-head">
                <i><a href="{% url 'profile' %}">
                        <ion-icon name="arrow-back-circle-outline"></ion-icon>
                    </a>
                </i>
                <div class="password-confirm-head-h1-div">
                    <h2>Update Your Profile</h2>
                </div>
            </div>

            <form method="post" enctype="multipart/form-data" id="profile_update_form">
                {% csrf_token %}

                <div class="form-group-div m-b0">
                    <div class="profile-image-div">
                        <div class="profile-image-preview" id="openUploadButton">
                            <img id="profileImage" src="{{ user_profile.profile_picture.url }}"
                                data-default="{% static 'mainapp/images/home/default.png' %}" alt="Profile Image">
                            <span class="edit-icon">
                                <ion-icon name="pencil-sharp"></ion-icon>
                            </span>
                        </div>
                        <div class="image-btn-div">
                            <input type="hidden" name="set_default_picture" id="setDefaultPictureField" value="false">
                            <button type="button" id="setDefaultButton" class="set-default-btn">Set Default</button>
                            <button type="button" id="revertImage" class="revert-btn"
                                style="display: none;">Revert</button>
                        </div>
                    </div>
                </div>

                <input type="file" id="imageUpload" name="profile_picture" accept="image/*" style="display: none;">

                <div class="form-group-div">
                    <label for="id_first_name">First Name:</label>
                    <div class="form-group">
                        {{ form.first_name }}
                    </div>
                </div>

                <div class="form-group-div">
                    <label for="id_last_name">Last Name:</label>
                    <div class="form-group">
                        {{ form.last_name }}
                    </div>
                </div>

                <div class="form-group-div">
                    <label for="id_email">Email:</label>
                    <div class="form-group">
                        {{ form.email }}
                    </div>
                </div>

                <div class="form-group-div">
                    <label for="id_phone_number">Phone Number:</label>
                    <div class="form-group">
                        {{ form.phone_number }}
                    </div>
                </div>

                <button type="submit" class="btn">Update Profile</button>
            </form>
        </div>
    </div>
</div>

<!-- image upload popup -->
<div class="upload-popup" id="uploadPopup">
    <div class="dashed-border" id="drop-area-popup" onclick="document.getElementById('imageUpload').click();">
        <div class="upload-icon"><ion-icon name="arrow-up-circle-outline"></ion-icon></div>
        <div class="upload-text">
            Drag and drop or
            <span style="color: #673ab7;">Click here</span>
            to upload Image.
        </div>
        <div class="file-size-info">Image size must be less than 5 MB</div>
        <div class="file-name" id="fileName"></div>
    </div>
</div>

<script src="{% static 'mainapp/js/update-profile.js' %}"></script>

{% endblock %}